package com.bulk16.app;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
    final int INK=Color.rgb(16,24,40), MUTED=Color.rgb(102,112,133), BG=Color.rgb(246,248,251), LINE=Color.rgb(228,231,236), GREEN=Color.rgb(27,127,90), GREEN_LIGHT=Color.rgb(232,245,239), WHITE=Color.WHITE, ORANGE=Color.rgb(181,71,8);
    LinearLayout root, content, nav; SharedPreferences prefs; int selectedTab=0; long startDate;
    String[] days={"Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"};
    String[] names={"Upper A","Lower A + Abs","Rest / Study","Upper B","Lower B + Abs","Optional Activity","Complete Rest"};
    String[][] sessions={
      {"Dumbbell Floor Press|4|6–12|2 min|Main chest press; controlled lowering.","One-Arm Dumbbell Row|4|8–15/side|90 sec|Pull elbow toward hip; avoid twisting.","Dumbbell Shoulder Press|3|8–12|90 sec|Controlled reps; don't overarch lower back.","Dumbbell Lateral Raise|3|12–20|45–60 sec|Strict reps; don't swing.","Dumbbell Rear-Delt Fly|3|12–20|45–60 sec|Move through the rear shoulder, not momentum.","Dumbbell Curl|2|8–15|60 sec|Full controlled range.","Overhead Dumbbell Triceps Extension|2|10–15|60 sec|Controlled stretch; don't force the range."},
      {"Bulgarian Split Squat|4|8–15/leg|90–120 sec|Priority movement; stable stance and controlled depth.","Dumbbell Romanian Deadlift|4|8–15|90–120 sec|2–3 sec lowering; keep spine controlled.","Goblet Squat|3|12–20|90 sec|Use a 3-sec eccentric and pause if 18 kg is too easy.","Dumbbell Calf Raise|4|12–25|45–60 sec|Pause at the top; use one leg when needed.","Reverse Crunch|3|10–20|45–60 sec|Curl pelvis upward; avoid swinging.","Dumbbell Suitcase Hold|3|30–60 sec/side|45–60 sec|Stay tall; resist side-bending."},
      {"Dumbbell Pullover|3|10–15|75–90 sec|Controlled range; stop if shoulders feel uncomfortable.","One-Arm Dumbbell Row|3|10–15/side|90 sec|Drive elbow back; controlled lowering.","Dumbbell Floor Press|3|8–15|90–120 sec|Slightly higher reps than Monday.","Dumbbell Arnold Press|3|8–15|90 sec|Only rotate through a comfortable pain-free range.","Dumbbell Lateral Raise|4|12–20|45–60 sec|Strict form; shoulders are a priority.","Rear-Delt Row / Rear-Delt Fly|3|12–20|45–60 sec|Focus on rear delts and upper back.","Hammer Curl|2|10–15|60 sec|Neutral grip; controlled reps.","Lying Dumbbell Triceps Extension|2|10–15|60 sec|Controlled elbow movement."},
      {"Bulgarian Split Squat|3|10–15/leg|90–120 sec|Use a slightly different stance if comfortable.","Dumbbell Romanian Deadlift|3|10–15|90–120 sec|Controlled hip hinge.","Dumbbell Reverse Lunge|3|10–15/leg|90 sec|Stable step and controlled descent.","Dumbbell Glute Bridge|3|12–20|60–90 sec|Pause 1–2 sec at the top.","Single-Leg Calf Raise|4|12–25|45–60 sec|Full controlled range.","Lying Leg Raise|3|8–15|45–60 sec|Avoid swinging; control the descent.","Plank|2|45–90 sec|45–60 sec|Brace the entire trunk; stop before form breaks."}
    };
    int[] workoutDayIdx={0,1,3,4};
    String[] periods={"Foundation","Progression","Deload","Hard Block","Final Block"};

    @Override public void onCreate(Bundle b){ super.onCreate(b); prefs=getSharedPreferences("bulk16",0); startDate=prefs.getLong("startDate",0); if(startDate==0){startDate=stripTime(System.currentTimeMillis()); prefs.edit().putLong("startDate",startDate).apply();} buildShell(); showHome(); }
    long stripTime(long x){Calendar c=Calendar.getInstance();c.setTimeInMillis(x);c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);return c.getTimeInMillis();}
    int week(){long diff=Math.max(0,stripTime(System.currentTimeMillis())-startDate);return Math.min(16,(int)(diff/(7L*24*60*60*1000))+1);}
    int todayIndex(){Calendar c=Calendar.getInstance();int d=c.get(Calendar.DAY_OF_WEEK);return d==Calendar.SUNDAY?6:d-2;}
    String period(int w){if(w<=4)return periods[0];if(w<=8)return periods[1];if(w==9)return periods[2];if(w<=13)return periods[3];return periods[4];}
    TextView tv(String s,float sp,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(INK);t.setTypeface(null,bold?1:0);t.setPadding(0,3,0,3);return t;}
    GradientDrawable bg(int color,float radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(radius);return g;}
    TextView chip(String s,int color,int textColor){TextView t=tv(s,12,true);t.setTextColor(textColor);t.setGravity(Gravity.CENTER);t.setPadding(12,7,12,7);t.setBackground(bg(color,30));return t;}
    Button button(String s,boolean filled){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(14);b.setTypeface(null,1);b.setPadding(16,0,16,0);b.setBackground(bg(filled?GREEN:WHITE,28));b.setTextColor(filled?WHITE:INK);return b;}
    TextView divider(){TextView v=new TextView(this);v.setBackgroundColor(LINE);v.setHeight(1);return v;}
    void buildShell(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(18,16,18,20);ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));nav=new LinearLayout(this);nav.setPadding(6,6,6,8);nav.setBackgroundColor(WHITE);String[] labels={"Home","Workout","Plan","Progress","Nutrition"};for(int i=0;i<labels.length;i++){final int tab=i;Button b=button(labels[i],false);b.setTextSize(11);b.setOnClickListener(v->{selectedTab=tab;renderTab();});nav.addView(b,new LinearLayout.LayoutParams(0,58,1));}root.addView(nav);setContentView(root);}
    void renderTab(){if(selectedTab==0)showHome();else if(selectedTab==1)showWorkout();else if(selectedTab==2)showPlan();else if(selectedTab==3)showProgress();else showNutrition();}
    void clear(){content.removeAllViews();}
    void header(String title,String subtitle){content.addView(tv(title,28,true));if(subtitle!=null)content.addView(tv(subtitle,14,false));Space sp=new Space(this);content.addView(sp,new LinearLayout.LayoutParams(1,10));}
    LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(16,15,16,15);c.setBackground(bg(WHITE,22));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,6,0,10);content.addView(c,p);return c;}
    void addRow(LinearLayout p,View v){p.addView(v,new LinearLayout.LayoutParams(-1,-2));}
    void showHome(){clear();int w=week(), d=todayIndex();header("BULK 16","Your 16-week dumbbell hypertrophy companion");LinearLayout hero=card();LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView h=tv("WEEK "+w+" / 16",22,true);top.addView(h,new LinearLayout.LayoutParams(0,-2,1));top.addView(chip(period(w),w==9?Color.rgb(255,243,224):GREEN_LIGHT,w==9?ORANGE:GREEN));hero.addView(top);hero.addView(tv("\n"+days[d]+"  •  "+names[d],18,true));hero.addView(tv(d==0||d==1||d==3||d==4?"45–60 min target":"Recovery / study day",13,false));Button start=button(d==0||d==1||d==3||d==4?"Start Today's Workout":"View Recovery Guidance",true);hero.addView(start,new LinearLayout.LayoutParams(-1,56));start.setOnClickListener(v->{if(d==0||d==1||d==3||d==4)showWorkout();else showPlan();});
      LinearLayout p=card();p.addView(tv("16-WEEK ROADMAP",14,true));p.addView(tv("Weeks 1–4  Foundation   •   5–8  Progression   •   9  Deload   •   10–13  Hard   •   14–16  Final",13,false));
      LinearLayout stats=card();stats.addView(tv("YOUR DASHBOARD",14,true));int completed=countCompleted();stats.addView(tv(completed+" / 64 workouts completed",22,true));stats.addView(tv("Keep logging every working set. Most sets should finish around 1–3 RIR.",13,false));
      LinearLayout quick=card();quick.addView(tv("QUICK TOOLS",14,true));Button pr=button("Log bodyweight / nutrition",false);quick.addView(pr,new LinearLayout.LayoutParams(-1,52));pr.setOnClickListener(v->{selectedTab=4;showNutrition();});Button pg=button("View progression",false);quick.addView(pg,new LinearLayout.LayoutParams(-1,52));pg.setOnClickListener(v->{selectedTab=3;showProgress();});
      if(w==9){LinearLayout del=card();del.addView(tv("DELOAD WEEK",18,true));del.addView(tv("Reduce sets by roughly 40–50%. Keep the movements, but avoid grinding.",13,false));}
      LinearLayout rule=card();rule.addView(tv("NON-NEGOTIABLES",14,true));rule.addView(tv("Train 4 days/week • Log every set • Progress over time • Controlled surplus • 1.6–2.2 g protein/kg/day • 7–9 h sleep",13,false)); }
    int currentWorkoutIndex(){int d=todayIndex();if(d==0)return 0;if(d==1)return 1;if(d==3)return 2;if(d==4)return 3;return -1;}
    void showWorkout(){clear();int idx=currentWorkoutIndex(), w=week();if(idx<0){header(names[todayIndex()],"Today is a recovery / study day");LinearLayout c=card();c.addView(tv("Recovery is part of the program.",20,true));c.addView(tv("Wednesday: rest + study. Saturday: optional light activity / study. Sunday: complete rest.",14,false));return;}header(names[todayIndex()],"Week "+w+"  •  "+period(w));if(w==9){LinearLayout c=card();c.addView(tv("DELOAD",16,true));c.addView(tv("Reduce total sets by roughly 40–50% and avoid grinding reps.",13,false));}
      for(int i=0;i<sessions[idx].length;i++)exerciseCard(idx,i,w);
      Button finish=button("✓  Finish workout",true);content.addView(finish,new LinearLayout.LayoutParams(-1,58));finish.setOnClickListener(v->{prefs.edit().putInt("done_"+w+"_"+idx,1).apply();Toast.makeText(this,"Workout saved.",Toast.LENGTH_SHORT).show();selectedTab=3;showProgress();}); }
    void exerciseCard(int idx,int ex,int w){String[] q=sessions[idx][ex].split("\\|",-1);LinearLayout c=card();LinearLayout titleRow=new LinearLayout(this);titleRow.setGravity(Gravity.CENTER_VERTICAL);TextView title=tv((ex+1)+"  "+q[0],17,true);titleRow.addView(title,new LinearLayout.LayoutParams(0,-2,1));titleRow.addView(chip(q[1]+" × "+q[2],GREEN_LIGHT,GREEN));c.addView(titleRow);c.addView(tv("Rest "+q[3],12,true));c.addView(tv(q[4],12,false));c.addView(divider());int sets=Integer.parseInt(q[1]);for(int s=1;s<=sets;s++){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView sn=tv("Set "+s,13,true);row.addView(sn,new LinearLayout.LayoutParams(48,52));EditText kg=input("kg");EditText reps=input("reps");EditText rir=input("RIR");row.addView(kg,new LinearLayout.LayoutParams(0,52,1));row.addView(reps,new LinearLayout.LayoutParams(0,52,1));row.addView(rir,new LinearLayout.LayoutParams(0,52,1));CheckBox check=new CheckBox(this);check.setText("Done");check.setTextSize(11);row.addView(check,new LinearLayout.LayoutParams(68,52));String key="log_"+w+"_"+idx+"_"+ex+"_"+s;kg.setText(prefs.getString(key+"kg",""));reps.setText(prefs.getString(key+"reps",""));rir.setText(prefs.getString(key+"rir",""));View.OnFocusChangeListener save=(v,f)->{if(!f)prefs.edit().putString(key+"kg",kg.getText().toString()).putString(key+"reps",reps.getText().toString()).putString(key+"rir",rir.getText().toString()).apply();};kg.setOnFocusChangeListener(save);reps.setOnFocusChangeListener(save);rir.setOnFocusChangeListener(save);c.addView(row);}
      Button timer=button("Start rest timer  •  "+q[3],false);c.addView(timer,new LinearLayout.LayoutParams(-1,46));timer.setOnClickListener(v->restDialog(q[3])); }
    EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(13);e.setSingleLine(true);e.setInputType(2|8192);e.setPadding(7,0,7,0);e.setBackground(bg(BG,14));return e;}
    void restDialog(String rest){int sec=60;try{if(rest.contains("90"))sec=90;else if(rest.contains("120"))sec=120;else if(rest.contains("75"))sec=75;else if(rest.contains("60"))sec=60;else if(rest.contains("45"))sec=45;}catch(Exception ignored){}final Dialog dialog=new Dialog(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(28,24,28,24);box.setBackground(bg(WHITE,28));TextView t=tv("REST",16,true);t.setGravity(Gravity.CENTER);box.addView(t);TextView timer=tv(String.format(Locale.US,"%02d:%02d",sec/60,sec%60),48,true);timer.setGravity(Gravity.CENTER);box.addView(timer);Button close=button("Close",false);box.addView(close,new LinearLayout.LayoutParams(-1,54));close.setOnClickListener(v->dialog.dismiss());dialog.setContentView(box);Window w=dialog.getWindow();if(w!=null)w.setBackgroundDrawable(bg(WHITE,28));dialog.show();new CountDownTimer(sec*1000L,1000){public void onTick(long m){timer.setText(String.format(Locale.US,"%02d:%02d",m/60000,(m/1000)%60));}public void onFinish(){timer.setText("00:00");timer.setTextColor(GREEN);}}.start();}
    void showPlan(){clear();int w=week();header("16-WEEK PLAN","Tap a day to see the session structure");LinearLayout weeks=card();weeks.addView(tv("CURRENT BLOCK",14,true));weeks.addView(tv("Week "+w+" — "+period(w),20,true));weeks.addView(tv(periodDescription(w),13,false));for(int i=0;i<7;i++){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(0,7,0,7);TextView day=tv(days[i],15,true);r.addView(day,new LinearLayout.LayoutParams(0,-2,1));r.addView(tv(names[i],13,false));weeks.addView(r);}
      LinearLayout rules=card();rules.addView(tv("PROGRESSION",16,true));rules.addView(tv("Double progression: keep the same weight until you reach the top of the rep range with good form across all prescribed sets. Then increase weight and build reps again.",13,false));rules.addView(tv("\nIf 18 kg becomes too light: use unilateral variations, higher reps, slower eccentrics, pauses and safe increases in ROM. Don't turn every set into sloppy 30–40-rep work.",13,false));
      LinearLayout rir=card();rir.addView(tv("RIR GUIDE",16,true));rir.addView(tv("Weeks 1–4: 2–3 RIR\nWeeks 5–8: 1–2 RIR\nWeek 9: Deload\nWeeks 10–13: 1–2 RIR\nWeeks 14–16: push progression; isolation can occasionally reach 0–1 RIR if technique remains safe.",13,false)); }
    String periodDescription(int w){if(w<=4)return"Technique + foundation. Learn movements and establish baseline numbers.";if(w<=8)return"Add reps, then weight when the top of the range is reached.";if(w==9)return"Deload: reduce sets roughly 40–50% and avoid grinding.";if(w<=13)return"Return to progressive training, mostly 1–2 RIR.";return"Final hard block. Push progression while keeping compounds controlled.";}
    int countCompleted(){int n=0;for(int w=1;w<=16;w++)for(int d=0;d<4;d++)n+=prefs.getInt("done_"+w+"_"+d,0);return n;}
    void showProgress(){clear();header("PROGRESS","Performance trends and consistency");int completed=countCompleted();LinearLayout c=card();c.addView(tv("WORKOUTS",14,true));c.addView(tv(completed+" / 64",34,true));c.addView(tv("completed across the 16-week program",13,false));ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(64);bar.setProgress(completed);c.addView(bar,new LinearLayout.LayoutParams(-1,18));
      LinearLayout b=card();b.addView(tv("BLOCK STATUS",14,true));for(int i=1;i<=16;i++){TextView row=tv("Week "+i+"   "+period(i),13,false);if(i==week())row.setTypeface(null,1);b.addView(row);}
      LinearLayout d=card();d.addView(tv("HOW TO PROGRESS",16,true));d.addView(tv("Record exercise, weight, reps and optionally RIR. Aim to beat your previous performance over time. If progress stalls, check food, sleep, recovery, execution and whether the available weight is sufficient.",13,false)); }
    void showNutrition(){clear();header("NUTRITION","Controlled bulk basics from the program");LinearLayout calc=card();calc.addView(tv("PROTEIN TARGET",14,true));EditText bw=input("Bodyweight in kg");calc.addView(bw,new LinearLayout.LayoutParams(-1,54));Button go=button("Calculate 1.6–2.2 g/kg",true);calc.addView(go,new LinearLayout.LayoutParams(-1,54));TextView result=tv("Enter your bodyweight above.",14,false);result.setPadding(0,12,0,0);calc.addView(result);go.setOnClickListener(v->{try{double x=Double.parseDouble(bw.getText().toString());result.setText(String.format(Locale.US,"Protein target: %.0f–%.0f g/day",x*1.6,x*2.2));prefs.edit().putFloat("bw",(float)x).apply();}catch(Exception e){result.setText("Enter a valid bodyweight.");}});
      LinearLayout surplus=card();surplus.addView(tv("CONTROLLED BULK",16,true));surplus.addView(tv("Starting point: roughly 10–20% calorie surplus. Target bodyweight increase: about 0.25–0.5% per week. Faster is not automatically better.",13,false));
      LinearLayout foods=card();foods.addView(tv("EASY FOOD OPTIONS",16,true));foods.addView(tv("Carbs: rice, oats, potatoes, dosa, idli, chapati, bread, bananas, fruit, cereal, pasta.\n\nProtein: eggs, chicken, fish, milk, curd, paneer, soy, dal, whey if convenient.\n\nFats: peanuts, peanut butter, nuts, eggs, dairy, olive oil, and other calorie-dense whole foods.",13,false));
      LinearLayout rec=card();rec.addView(tv("POST-WORKOUT",16,true));rec.addView(tv("Milk + oats + banana + peanut butter + eggs is a simple high-calorie, protein-rich option. Adjust quantities to your targets.",13,false));
      LinearLayout recovery=card();recovery.addView(tv("RECOVERY",16,true));recovery.addView(tv("The program recommends 7–9 hours of sleep. If you wake around 5:25 AM, bedtime needs to be early enough to make that target realistic.",13,false));recovery.addView(tv("\nCreatine monohydrate is listed at 3–5 g every day; timing is not important and cycling is not required.",13,false)); }
}
